tests:
  - name: "Test Main Bucle Ixir"
    setup: mvn -B package --file pom.xml
    run: mvn -Dtest=AppTest#testMainBucleIxit test
    points: 1
  - name: "Inicialitzar Preus"
    setup: mvn -B package --file pom.xml
    run: mvn -Dtest=AppTest#testInicialitzarPreus test
    points: 2
  - name: "Mostrar Menú"
    setup: mvn -B package --file pom.xml
    run: mvn -Dtest=AppTest#testMostrarMenu test
    points: 1
  - name: "Gestionar Opció Invàlida"
    setup: mvn -B package --file pom.xml
    run: mvn -Dtest=AppTest#testGestionarOpcioInvalida test
    points: 1
  - name: "Reservar Habitació"
    setup: mvn -B package --file pom.xml
    run: mvn -Dtest=AppTest#testReservarHabitacioCreaReservaIDisminueixDisponibilitat test
    points: 3
  - name: "Seleccionar Tipus Habitació Suite"
    setup: mvn -B package --file pom.xml
    run: mvn -Dtest=AppTest#testSeleccionarTipusHabitacioSuite test
    points: 1
  - name: "Seleccionar Tipus Habitació Disponible"
    setup: mvn -B package --file pom.xml
    run: mvn -Dtest=AppTest#testSeleccionarTipusHabitacioDisponibleAmbDisponibilitat test
    points: 1
  - name: "Seleccionar Tipus Habitació Sense Disponibilitat"
    setup: mvn -B package --file pom.xml
    run: mvn -Dtest=AppTest#testSeleccionarTipusHabitacioDisponibleSenseDisponibilitat test
    points: 1
  - name: "Seleccionar Serveis Sense Cap Servei"
    setup: mvn -B package --file pom.xml
    run: mvn -Dtest=AppTest#testSeleccionarServeisSenseCapServei test
    points: 2
  - name: "Calcular Preu Total Habitació + Servei"
    setup: mvn -B package --file pom.xml
    run: mvn -Dtest=AppTest#testCalcularPreuTotalHabitacioMesServei test
    points: 2
  - name: "Generar Codi Reserva Rang i Únic"
    setup: mvn -B package --file pom.xml
    run: mvn -Dtest=AppTest#testGenerarCodiReservaRangIUnic test
    points: 3
  - name: "Alliberar Habitació"
    setup: mvn -B package --file pom.xml
    run: mvn -Dtest=AppTest#testAlliberarHabitacioIncrementaDisponibilitatIEliminaReserva test
    points: 3
  - name: "Consultar Disponibilitat"
    setup: mvn -B package --file pom.xml
    run: mvn -Dtest=AppTest#testConsultarDisponibilitatMostraTaula test
    points: 1
  - name: "Llistar Reserves Per Tipus"
    setup: mvn -B package --file pom.xml
    run: mvn -Dtest=AppTest#testLlistarReservesPerTipusFiltraCorrectament test
    points: 2
  - name: "Obtindre Reserva"
    setup: mvn -B package --file pom.xml
    run: mvn -Dtest=AppTest#testObtindreReservaMostraReserva test
    points: 2
  - name: "Obtindre Reserva Per Tipus"
    setup: mvn -B package --file pom.xml
    run: mvn -Dtest=AppTest#testObtindreReservaPerTipusMostraNomésEixeTipus test
    points: 2
  - name: "Mostrar Dades Reserva"
    setup: mvn -B package --file pom.xml
    run: mvn -Dtest=AppTest#testMostrarDadesReserva test
    points: 2